version: 2

sources:
  - name: hivdb
    database: AwsDataCatalog
    schema: hivdb_tce
    tables:
      - name: tce_measurements
      - name: tce_case
      - name: tce_isolates
      - name: tce_mutations
      - name: tce_treatments