version: 2

sources:
  - name: hiv_analysis
    database: hiv_analysis
    schema: hiv_analysis
    tables:
      - name: genotype_phenotype_pi
      - name: genotype_phenotype_nrti
      - name: genotype_phenotype_nnrti
      - name: genotype_phenotype_ini
      - name: genotype_phenotype_cai
