services:
  kestra:
    image: kestra/kestra:latest
    user: "root"
    command: server local
    ports:
      - "8080:8080"
      - "8501:8501"
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PROJECT_ROOT}:/app/hiv-resistance-analytics
      - ${AWS_DIR}:/root/.aws:ro
      - ${DBT_DIR}:/root/.dbt:ro
      - ${HOME}/.streamlit:/root/.streamlit:ro
    environment:
      KESTRA_CONFIGURATION: |
        kestra:
          local-files:
            allowed-paths:
              - /app/hiv-resistance-analytics
            tutorial:
              enabled: false

        micronaut:
          io:
            watch:
              enabled: true
              paths:
                - /app/hiv-resistance-analytics/orchestration/flows

volumes:
  kestra-data: